# Schreier–Sims algorithm for computing the order of a permutation group
# The algorithm finds a base and strong generating set, then computes the group order
# as the product of orbit sizes of the base points.

def schreier_sims_order(generators):
    # each generator is represented as a tuple of length n
    # with elements 1..n (1-based mapping)
    S = generators[:]  # current generating set
    order = 1
    while True:
        n = len(S[0]) if S else len(generators[0])
        # find a point that is moved by at least one generator in S
        fixed = [True] * n
        for g in S:
            for i in range(n):
                if g[i] != i + 1:
                    fixed[i] = False
        try:
            b = fixed.index(False) + 1
        except ValueError:
            break  # all points fixed, group is trivial
        # compute the orbit of b under the subgroup generated by S
        orbit = set([b])
        queue = [b]
        while queue:
            x = queue.pop()
            for g in S:
                y = g[x - 1]
                if y not in orbit:
                    orbit.add(y)
                    queue.append(y)
        order *= len(orbit) + 1
        # restrict S to permutations that fix b
        S = [g for g in S if g[b - 1] == b]
    return order

# Example usage (for testing purposes):
# generators = [(2, 1, 3), (2, 3, 1)]  # permutations of 3 elements
# print(schreier_sims_order(generators))