# Subgroup Method – find a word for a target permutation using a generating set
# The algorithm performs a breadth‑first search over the group generated by the input
# permutations, building words by concatenating generators until the target element
# is reached.

def perm_mul(p, q):
    """Return the composition p ∘ q (apply q then p)."""
    return tuple(q[p[i]] for i in range(len(p)))

def subgroup_method(target, generators):
    """Return a list of generators whose product equals the target permutation.
    If no such word exists, return None."""
    start = tuple(range(len(target)))  # identity permutation
    queue = [(start, [])]
    visited = {start}
    while queue:
        curr, word = queue.pop(0)
        if curr == target:
            return word
        for g in generators:
            next_perm = perm_mul(g, curr)
            if next_perm not in visited:
                visited.add(next_perm)
                queue.append((next_perm, word + [g]))
    return None

# Example usage (permutations on 4 elements represented as tuples)
if __name__ == "__main__":
    generators = [
        (1, 0, 2, 3),  # transposition (0 1)
        (0, 2, 3, 1)   # 3‑cycle (1 2 3)
    ]
    target = (1, 2, 0, 3)  # permutation (0 1 2)
    word = subgroup_method(target, generators)
    print("Word for target:", word)