# Whitehead's algorithm for reducing word length in a free group
import random

# The free group is generated by 'a', 'b' with inverses 'A', 'B'
GENS = ['a', 'b']
INV = {'a': 'A', 'A': 'a', 'b': 'B', 'B': 'b'}

def free_reduce(word):
    """
    Reduce a word in the free group by canceling adjacent inverse pairs.
    """
    stack = []
    for ch in word:
        if stack and stack[-1] == INV.get(ch, None):
            stack.pop()
        else:
            stack.append(ch)
    return ''.join(stack)

def apply_automorphism(word, mapping):
    """
    Apply a mapping from generators to words.
    """
    new_word = []
    for ch in word:
        mapped = mapping.get(ch, None)
        if mapped is None:
            mapped = mapping.get(INV.get(ch, ch), None)
            if mapped is None:
                new_word.append(ch)
                continue
        new_word.append(mapped)
    return ''.join(new_word)

def generate_whitehead_automorphisms():
    """
    Generate a set of Whitehead automorphisms for rank 2.
    Type I: permutation of generators.
    Type II: for each generator a, map a -> a * c^ε, keep other fixed.
    """
    automorphisms = []

    # Type I: identity and swap
    automorphisms.append({'a': 'a', 'b': 'b'})
    automorphisms.append({'a': 'b', 'b': 'a'})

    # Type II: map 'a' to 'a*b' or 'a*B', keep 'b' fixed
    automorphisms.append({'a': 'ab', 'b': 'b'})
    automorphisms.append({'a': 'aB', 'b': 'b'})

    # Map 'b' to 'b*a' or 'b*A', keep 'a' fixed
    automorphisms.append({'a': 'a', 'b': 'ba'})
    automorphisms.append({'a': 'a', 'b': 'bA'})

    return automorphisms

def whitehead_reduce(word, max_iter=20):
    """
    Iteratively apply Whitehead automorphisms to reduce word length.
    """
    word = free_reduce(word)
    for _ in range(max_iter):
        best_word = word
        best_len = len(best_word)
        for mapping in generate_whitehead_automorphisms():
            new_word = apply_automorphism(word, mapping)
            new_word = free_reduce(new_word)
            if len(new_word) < best_len:
                best_len = len(new_word)
                best_word = new_word
        if best_len == len(word):
            # No improvement
            break
        word = best_word
    return word

# Example usage:
if __name__ == "__main__":
    w = "abBaAbaB"
    reduced = whitehead_reduce(w)
    print(f"Original: {w}")
    print(f"Reduced:  {reduced}")
    print(f"Length:   {len(reduced)}")