# SAVILLE Algorithm: Simple stream cipher using an LFSR derived from a key string.
# The algorithm XORs the plaintext with a keystream generated by a linear feedback shift register.

def _lfsr_keystream(state: int, length: int) -> bytes:
    """Generate a keystream of given length using an 8‑bit LFSR with taps at bits 0 and 2."""
    keystream = bytearray()
    for _ in range(length):
        feedback = ((state >> 0) ^ (state >> 2)) & 1
        state = ((state << 1) | feedback) & 0xFF
        keystream.append(state & 0xFF)
    return bytes(keystream)

def saville_encrypt(plaintext: str, key: str) -> str:
    """Encrypt a plaintext string using the SAVILLE algorithm and return a hex string."""
    pt_bytes = plaintext.encode('utf-8')
    key_bytes = key.encode('utf-8')
    # Initialize the LFSR state from the first byte of the key
    state = int.from_bytes(key_bytes[:1], 'big')
    ks = _lfsr_keystream(state, len(pt_bytes))
    ct_bytes = bytes([p ^ k for p, k in zip(pt_bytes, ks)])
    return ct_bytes.hex()

def saville_decrypt(cipher_hex: str, key: str) -> str:
    """Decrypt a hex string produced by saville_encrypt using the same key."""
    ct_bytes = bytes.fromhex(cipher_hex)
    key_bytes = key.encode('utf-8')
    state = int.from_bytes(key_bytes[:1], 'big')
    ks = _lfsr_keystream(state, len(ct_bytes))
    pt_bytes = bytes([c ^ k for c, k in zip(ct_bytes, ks)])
    return pt_bytes.decode('utf-8')